local theme = {}

function theme.setup()

    local styles = { comments = "italic", functions = "bold", keywords = "italic", variables = "NONE", }

    local color = require("cs.palette").colors

    theme.highlights = {
        -- Base highlights
        Boolean = { fg = color.color5 },
        Character = { fg = color.color12 },
        ColorColumn = { bg = color.none },
        Comment = { fg = color.comment, style = options.styles.comments },
        Conceal = { fg = color.color4, bg = color.background },
        Conditional = { fg = color.color6 },
        Constant = { fg = color.color5 },
        Cursor = { fg = color.foreground, bg = color.foreground },
        CurSearch = { link = "IncSearch" },
        CursorColumn = { bg = color.background },
        CursorIM = { fg = color.foreground, bg = color.foreground },
        CursorLine = { bg = color.none },
        CursorLineNr = { fg = color.foreground },
        Debug = { fg = color.color1 },
        Define = { fg = color.color5 },
        Delimiter = { fg = color.foreground },
        DiffAdd = { bg = color.color4, fg = color.black },
        DiffChange = { bg = color.color5, fg = color.black },
        DiffDelete = { bg = color.color1, fg = color.black },
        DiffText = { bg = color.color1, fg = color.black },
        Directory = { fg = color.color17 },
        EndOfBuffer = { fg = color.background },
        Error = { fg = color.color1, bg = color.background },
        ErrorMsg = { fg = color.color1, bg = color.background },
        Exception = { fg = color.color6 },
        Float = { fg = color.color5 },
        FloatBorder = { fg = color.color17 },
        FoldColumn = { fg = color.color4, bg = color.background },
        Folded = { fg = color.color4, bg = color.background },
        Function = { fg = color.color6, style = options.styles.functions },
        Identifier = { fg = color.color5 },
        Ignore = { fg = color.color7, bg = color.background },
        IncSearch = { fg = color.black, bg = color.color10 },
        Include = { fg = color.color6 },
        Keyword = { fg = color.color6, style = options.styles.keywords },
        Label = { fg = color.color4 },
        LineNr = { fg = color.linenr or color.color8 },
        Macro = { fg = color.color6 },
        MatchParen = { fg = color.color4, bg = color.background },
        ModeMsg = { fg = color.foreground, bg = color.background },
        MoreMsg = { fg = color.color5 },
        MsgArea = { fg = color.foreground, bg = color.background },
        MsgSeparator = { fg = color.foreground, bg = color.background },
        NonText = { fg = color.color1 },
        Normal = { fg = color.foreground, bg = color.background },
        NormalFloat = { bg = color.background },
        NormalNC = { fg = color.foreground, bg = color.background },
        Number = { fg = color.color3 },
        Operator = { fg = color.color6 },
        Pmenu = { fg = color.color17, bg = color.background },
        PmenuSbar = { bg = color.background },
        PmenuSel = { fg = color.black, bg = color.color4 },
        PmenuThumb = { bg = color.color2 },
        PreCondit = { fg = color.color6 },
        PreProc = { fg = color.color6 },
        Question = { fg = color.color5 },
        QuickFixLine = { bg = color.cursorline },
        qfLineNr = { fg = color.color4 },
        Repeat = { fg = color.color6 },
        Search = { fg = color.black, bg = color.color4 },
        SignColumn = { fg = color.background, bg = color.background },
        Special = { fg = color.color6 },
        SpecialChar = { fg = color.foreground },
        SpecialComment = { fg = color.color2 },
        SpecialKey = { fg = color.color4 },
        SpellBad = { fg = color.color2 },
        SpellCap = { fg = color.color6 },
        SpellLocal = { fg = color.color4 },
        SpellRare = { fg = color.color6 },
        Statement = { fg = color.color6 },
        StatusLine = { fg = color.foreground, bg = color.background },
        StatusLineNC = { bg = color.background, fg = color.background },
        Storage = { fg = color.color9 },
        StorageClass = { fg = color.color5 },
        String = { fg = color.color2 },
        Structure = { fg = color.color6 },
        Substitute = { fg = color.black, bg = color.color9 },
        TabLine = { fg = color.color2, bg = color.background },
        TabLineFill = { fg = color.foreground, bg = color.background },
        TabLineSel = { fg = color.foreground, bg = color.background },
        Tag = { fg = color.color4 },
        TermCursor = { fg = color.foreground, bg = color.foreground },
        TermCursorNC = { fg = color.foreground, bg = color.foreground },
        Title = { fg = color.color4, bold = true },
        Todo = { fg = color.color1, bg = color.background },
        Type = { fg = color.color5 },
        Typedef = { fg = color.color6 },
        Underlined = { fg = color.color2, underline = true },
        Variable = { fg = color.color5 },
        VertSplit = { fg = color.color0 },
        Visual = { bg = color.cursorline },
        VisualNOS = { bg = color.background },
        WarningMsg = { fg = color.color3, bg = color.background },
        Whitespace = { fg = color.color1 },
        WildMenu = { fg = color.color7, bg = color.color4 },
        lCursor = { fg = color.foreground, bg = color.foreground },
    }

    for group, hl in pairs(theme.highlights) do
        vim.api.nvim_set_hl(0, group, hl)
    end
end

return theme
